# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f5e69b5c-06d0-4537-9b62-6adc63d52669";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f5e69b5c-06d0-4537-9b62-6adc63d52669".device = "/dev/disk/by-uuid/f5e69b5c-06d0-4537-9b62-6adc63d52669";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E2B8-07D3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-376d6ff5-efc1-4324-9b83-8517debce7e5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
